package com.truward.polymer.api.output;

import com.truward.polymer.naming.FqName;
import com.truward.polymer.output.FileType;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.Collection;

/**
 * A registry, that holds all the virtual files, generated by the code generator.
 *
 * @author Alexander Shabanov
 */
public interface OutputRegistry {

  @Nonnull
  <T extends ContentGenerator> VirtualFile<T> getOrCreate(@Nonnull FqName name,
                                                          @Nonnull FileType fileType,
                                                          @Nonnull Class<T> contentGeneratorClass);

  @Nonnull
  Collection<VirtualFile> getAll();

  void suppressGeneration(@Nonnull FqName path, @Nullable FileType fileType);
}
