package com.truward.polymer;

import com.truward.polymer.naming.FqName;

import javax.annotation.Nonnull;

/**
 * Represents a specification target, used in code generator for designating code generation targets.
 * Target will always have the corresponding implementation, generated by the corresponding code generation driver.
 *
 * @param <T> Interface class, which should have the corresponding implementation target.
 *
 * @author Alexander Shabanov
 */
public interface SpecificationTarget<T> {

    @Nonnull
    FqName getTargetName();

    void setTargetName(@Nonnull FqName name);

    @Nonnull
    T getTarget();
}
